motor_types:
  dmj4310:
    pmax: 12.5  
    vmax: 30.0 
    tmax: 10.0  
  dmj4340:
    pmax: 12.5  
    vmax: 10.0 
    tmax: 28.0  

robot_config:
  num_motors: 1
  motor_configs:
    - dmj4310
    - dmj4340
    - dmj4340
    - dmj4340
    - dmj4310
    - dmj4310
    - dmj4310
